(deftheme Drive-Dark
  "bgc")

(custom-theme-set-variables
 'Drive-Dark
 '(ansi-color-names-vector ["#292929" "#ff3333" "#aaffaa" "#aaeecc" "#aaccff" "#FF1F69" "#aadddd" "#999999"]))

(custom-theme-set-faces
 'Drive-Dark
 '(cursor ((t (:background "#020D0F" :foreground "#CCCCCC"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((t (:family "Sans Serif"))))
 '(escape-glyph ((t (:foreground "#68f6cb"))))
 '(minibuffer-prompt ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#aadddd"))))
 '(highlight ((t (:background "#020D0F" :foreground "#083039"))))
 '(region ((t (:foreground "#646E70"))))
 '(shadow ((t (:foreground "#5f5f5f"))))
 '(secondary-selection ((t (:background "#292929"))))
 '(trailing-whitespace ((t (:background "#F2777A" :foreground "#CDCDCD"))))
 '(font-lock-builtin-face ((t (:background "#161A24" :foreground "#e24297"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#646E70"))))
 '(font-lock-comment-face ((t (:foreground "#646E70"))))
 '(font-lock-constant-face ((t (:background "#0E1C1D" :foreground "#F99157"))))
 '(font-lock-doc-face ((t (:foreground "#646E70"))))
 '(font-lock-function-name-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#aaccff"))))
 '(font-lock-keyword-face ((t (:background "#051D22" :foreground "#19b6d8"))))
 '(font-lock-negation-char-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#ff3333"))))
 '(font-lock-preprocessor-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#ff8888"))))
 '(font-lock-regexp-grouping-backslash ((t (:background "#161A24" :foreground "#E24297"))))
 '(font-lock-regexp-grouping-construct ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#ff8888"))))
 '(font-lock-string-face ((t (:background "#0E1D21" :foreground "#FFBBBB"))))
 '(font-lock-type-face ((t (:background "#161A24" :foreground "#e24297"))))
 '(font-lock-variable-name-face ((t (:background "#0C1418" :foreground "#f27798"))))
 '(font-lock-warning-face ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#ff3333"))))
 '(button ((t (:background "#081724" :foreground "#afc0fd" :inherit nil :box (:line-width 2 :style released-button)))))
 '(link ((t (:weight normal :slant normal :underline t :inverse-video nil :foreground "#ccaaff"))))
 '(link-visited ((t (:weight normal :slant normal :underline t :inverse-video nil :foreground "#FF1F69"))))
 '(fringe ((t (:foreground "#5f5f5f" :background "#292929"))))
 '(header-line ((t (:foreground "#cccccc" :background "#292929" :weight normal :slant normal :underline nil :inverse-video t))))
 '(tooltip ((((class color)) (:inherit (variable-pitch) :foreground "black" :background "lightyellow")) (t (:inherit (variable-pitch)))))
 '(mode-line ((t (:foreground "#cccccc" :background "#292929" :weight normal :slant normal :underline nil :inverse-video t :box nil))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:foreground "#999999" :background "#292929" :weight normal :slant normal :underline nil :inverse-video t :box nil))))
 '(isearch ((t (:weight normal :slant normal :underline nil :inverse-video t :foreground "#ff8888" :background "#202020"))))
 '(isearch-fail ((t (:weight normal :slant normal :underline nil :inverse-video t :foreground "#ff8888" :background "#202020"))))
 '(lazy-highlight ((t (:weight normal :slant normal :underline nil :inverse-video t :foreground "#aaeecc" :background "#202020"))))
 '(match ((t (:foreground "#081724" :background "#bad6e2"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
 '(default ((t (:foreground "#cccccc" :background "#202020"))))
 '(custom-button ((t (:foreground "#aaaaaa" :background "#292929" :box (:line-width 2 :style released-button)))))
 '(custom-state ((t (:foreground "#aaffaa"))))
 '(flymake-errline ((t (:underline (:color "#ff3333" :style wave) :inherit default))))
 '(flymake-warnline ((t (:underline (:color "#ff8888" :style wave) :inherit default))))
 '(hl-line ((t (:background "#083039" :underline nil))))
 '(idle-highlight ((t (:background "#033340" :foreground nil))))
 '(ido-indicator ((t (:background "#ff694d" :foreground "#081724" :width condensed))))
 '(ido-only-match ((t (:foreground "#aaffaa"))))
 '(ido-subdir ((t (:foreground "#aaccff"))))
 '(info-menu-star ((t (:foreground "#ff694d"))))
 '(info-xref ((t (:weight normal :slant normal :underline t :inverse-video nil :foreground "#aaccff"))))
 '(org-hide ((t (:foreground "#202020"))))
 '(magit-header ((t (:background "#033340" :foreground "#afc0fd" :inherit nil))))
 '(magit-item-highlight ((t (:background "#033340" :foreground nil))))
 '(magit-diff-hunk-header ((t (:background "#1d5483"))))
 '(diff-file-header ((t (:background "#202020"))))
 '(diff-context ((t (:inherit diff-changed :foreground "#2872b2"))))
 '(diff-added ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#aaffaa"))))
 '(diff-removed ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#ff3333"))))
 '(outline-1 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#aaccff"))))
 '(outline-2 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#aadddd"))))
 '(outline-3 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#aaeecc"))))
 '(outline-4 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#ff3333"))))
 '(outline-5 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#cccccc"))))
 '(outline-6 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#5f5f5f"))))
 '(outline-7 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#ff8888"))))
 '(outline-8 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#ccaaff"))))
 '(success ((t (:background "#68f6cb" :foreground "#081724" :weight bold))))
 '(compilation-mode-line-exit ((t (:inherit compilation-info :background "#68f6cb" :weight bold))))
 '(compilation-mode-line-fail ((t (:inherit compilation-error :background "#ff694d" :weight bold))))
 '(erc-dangerous-host-face ((t (:foreground "#ff694d"))))
 '(erc-direct-msg-face ((t (:foreground "#ff694d"))))
 '(erc-error-face ((t (:foreground "#ff694d"))))
 '(erc-fool-face ((t (:foreground "#1d5483"))))
 '(erc-header-line ((t (:background "#fffed9" :foreground "#081724"))))
 '(erc-inverse-face ((t (:background "#d3f9ee" :foreground "#081724"))))
 '(erc-keyword-face ((t (:weight bold :underline nil :inverse-video nil :foreground "#aaeecc"))))
 '(erc-nick-msg-face ((t (:foreground "#ff694d" :weight bold))))
 '(erc-notice-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#aaccff"))))
 '(erc-pal-face ((t (:foreground "#afc0fd" :weight bold))))
 '(erc-prompt-face ((t (:background "#96a5d9" :foreground "#081724" :weight bold))))
 '(erc-timestamp-face ((t (:foreground "#5f5f5f"))))
 '(erc-input-face ((t (:foreground "#5f5f5f"))))
 '(erc-my-nick-face ((t (:foreground "#aaccff"))))
 '(erc-current-nick-face ((t (:foreground "#fffe4e"))))
 '(show-paren-match ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#aadddd" :background "#292929"))))
 '(show-paren-mismatch ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#ff3333" :background "#5f5f5f"))))
 '(sp-show-pair-match-face ((t (:inherit show-paren-match))))
 '(sp-show-pair-mismatch-face ((t (:inherit show-paren-mismatch))))
 '(sp-pair-overlay-face ((t (:inherit sp-show-pair-match-face))))
 '(ac-completion-face ((t (:foreground "#1d5483" :underline t))))
 '(ac-candidate-face ((t (:background "#d3f9ee" :foreground "#081724"))))
 '(ac-candidate-mouse-face ((t (:inherit ac-completion-face))))
 '(ac-selection-face ((t (:background "#1d5483"))))
 '(modeline ((t (:background "#465253" :foreground "#ffffff"))))
 '(font-lock-doc-string-face ((t (:weight normal :slant italic :underline nil :inverse-video nil :foreground "#5f5f5f"))))
 '(rainbow-delimiters-depth-1-face ((t (:foreground "#aadddd"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#aaeecc"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "#aaccff"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "#ff3333"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "#aaffaa"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "#aaccff"))))
 '(rainbow-delimiters-depth-7-face ((t (:foreground "#ff8888"))))
 '(rainbow-delimiters-depth-8-face ((t (:foreground "#FF1F69"))))
 '(rainbow-delimiters-depth-9-face ((t (:foreground "#cccccc"))))
 '(cua-rectangle ((t (:background "#141411"))))
 '(ido-first-match ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#aaffaa"))))
 '(whitespace-space ((t (:foreground "#292929"))))
 '(yas/field-highlight-face ((t (:background "#383830"))))
 '(error ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#ff3333"))))
 '(escape-glyph-face ((t (:foreground "#ff3333"))))
 '(linum ((t (:foreground "#5f5f5f" :background "#292929"))))
 '(menu ((t (:foreground "#cccccc" :background "#292929"))))
 '(vertical-border ((t (:foreground "#cccccc"))))
 '(comint-highlight-prompt ((t (:foreground "#aaccff"))))
 '(compilation-info ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#aaffaa"))))
 '(compilation-warning ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#ff8888"))))
 '(custom-button-mouse ((t (:weight normal :slant normal :underline nil :inverse-video t :foreground "#aaaaaa" :background "#292929" :inherit custom-button))))
 '(custom-button-pressed ((t (:weight normal :slant normal :underline nil :inverse-video t :foreground "#aaaaaa" :background "#292929" :box (:line-width 2 :style pressed-button) :inherit custom-button-mouse))))
 '(custom-changed ((t (:weight normal :slant normal :underline nil :inverse-video t :foreground "#aaccff" :background "#fcf4dc"))))
 '(custom-comment ((t (:foreground "#aaaaaa" :background "#292929"))))
 '(custom-comment-tag ((t (:foreground "#aaaaaa" :background "#292929"))))
 '(custom-documentation ((t (:inherit default))))
 '(custom-group-tag ((t (:foreground "#aaaaaa"))))
 '(custom-group-tag-1 ((t ((:weight bold :slant normal :underline nil :inverse-video nil) :foreground "#aaaaaa"))))
 '(custom-invalid ((t (:weight normal :slant normal :underline nil :inverse-video t :foreground "#ff3333" :background "#202020"))))
 '(custom-link ((t (:foreground "#ccaaff"))))
 '(custom-variable-tag ((t (:foreground "#aaaaaa"))))
 '(diff-changed ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#aaeecc"))))
 '(diff-refine-change ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#aaccff" :background "#202020"))))
 '(diff-header ((t (:foreground "#aaaaaa" :background "#202020"))))
 '(emacs-wiki-bad-link-face ((t (:weight normal :slant normal :underline t :inverse-video nil :foreground "#ff3333"))))
 '(emacs-wiki-link-face ((t (:weight normal :slant normal :underline t :inverse-video nil :foreground "#aaccff"))))
 '(emacs-wiki-verbatim-face ((t (:weight normal :slant normal :underline t :inverse-video nil :foreground "#999999"))))
 '(eshell-ls-archive ((t (:foreground "#FF1F69"))))
 '(eshell-ls-backup ((t (:foreground "#aaeecc"))))
 '(eshell-ls-clutter ((t (:foreground "#ff8888"))))
 '(eshell-ls-directory ((t (:foreground "#aaccff"))))
 '(eshell-ls-executable ((t (:foreground "#aaffaa"))))
 '(eshell-ls-missing ((t (:foreground "#ff3333"))))
 '(eshell-ls-product ((t (:foreground "#aaeecc"))))
 '(eshell-ls-readonly ((t (:foreground "#aaaaaa"))))
 '(eshell-ls-special ((t (:foreground "#ccaaff"))))
 '(eshell-ls-symlink ((t (:foreground "#aadddd"))))
 '(eshell-ls-unreadable ((t (:foreground "#999999"))))
 '(eshell-prompt ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#aaffaa"))))
 '(font-lock-color-constant-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#aaffaa"))))
 '(font-lock-reference-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#aadddd"))))
 '(font-lock-other-type-face ((t (:weight normal :slant italic :underline nil :inverse-video nil :foreground "#aaccff"))))
 '(font-lock-special-keyword-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#ff3333"))))
 '(font-lock-exit-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#ff3333"))))
 '(font-lock-other-emphasized-face ((t (:weight bold :underline nil :inverse-video nil :foreground "#ccaaff"))))
 '(info-xref-visited ((t (:foreground "#FF1F69" :inherit info-xref))))
 '(org-todo ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#202020" :background "#ff3333"))))
 '(org-done ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#aaffaa"))))
 '(org-todo-kwd-face ((t (:foreground "#ff3333" :background "#202020"))))
 '(org-done-kwd-face ((t (:foreground "#aaffaa" :background "#202020"))))
 '(org-project-kwd-face ((t (:foreground "#ccaaff" :background "#202020"))))
 '(org-waiting-kwd-face ((t (:foreground "#ff8888" :background "#202020"))))
 '(org-someday-kwd-face ((t (:foreground "#aaccff" :background "#202020"))))
 '(org-started-kwd-face ((t (:foreground "#aaeecc" :background "#202020"))))
 '(org-cancelled-kwd-face ((t (:foreground "#aaffaa" :background "#202020"))))
 '(org-delegated-kwd-face ((t (:foreground "#aadddd" :background "#202020"))))
 '(table-cell ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#cccccc" :background "#202020"))))
 '(speedbar-button-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#aaaaaa"))))
 '(speedbar-directory-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#ff8888"))))
 '(speedbar-file-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#aaffaa"))))
 '(speedbar-highlight-face ((t (:background "#292929"))))
 '(speedbar-selected-face ((t (:weight normal :slant normal :underline t :inverse-video nil :foreground "#aaeecc"))))
 '(speedbar-separator-face ((t (:weight normal :slant normal :underline nil :inverse-video t))))
 '(speedbar-tag-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#aaccff"))))
 '(widget-field ((t (:foreground "#aaaaaa" :background "#292929" :box (:line-width 1) :inherit default))))
 '(widget-single-line-field ((t (:inherit widget-field))))
 '(bm-fringe-face ((t (:background "#ff8888" :foreground "#202020"))))
 '(bm-fringe-persistent-face ((t (:background "#aaccff" :foreground "#202020"))))
 '(column-marker-1 ((t (:background "#5f5f5f"))))
 '(column-marker-2 ((t (:background "#aadddd"))))
 '(column-marker-3 ((t (:background "#ccaaff"))))
 '(jabber-activity-face ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#ff3333"))))
 '(jabber-activity-personal-face ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#aaccff"))))
 '(jabber-chat-error ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#ff3333"))))
 '(jabber-chat-prompt-foreign ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#ff3333"))))
 '(jabber-chat-prompt-local ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#aaccff"))))
 '(jabber-chat-prompt-system ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#aaffaa"))))
 '(jabber-chat-text-foreign ((t (:foreground "#aaaaaa"))))
 '(jabber-chat-text-local ((t (:foreground "#cccccc"))))
 '(jabber-chat-rare-time-face ((t (:weight normal :slant normal :underline t :inverse-video nil :foreground "#aaffaa"))))
 '(jabber-roster-user-away ((t (:weight normal :slant italic :underline nil :inverse-video nil :foreground "#aaffaa"))))
 '(jabber-roster-user-chatty ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#ff8888"))))
 '(jabber-roster-user-dnd ((t (:weight normal :slant italic :underline nil :inverse-video nil :foreground "#ff3333"))))
 '(jabber-roster-user-error ((t (:weight light :slant italic :foreground "#ff3333"))))
 '(jabber-roster-user-offline ((t (:foreground "#5f5f5f"))))
 '(jabber-roster-user-online ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#aaccff"))))
 '(jabber-roster-user-xa ((t (:weight normal :slant italic :underline nil :inverse-video nil :foreground "#FF1F69"))))
 '(git-gutter:modified ((t (:foreground "#ccaaff"))))
 '(git-gutter:added ((t (:foreground "#aaffaa"))))
 '(git-gutter:deleted ((t (:foreground "#ff3333"))))
 '(gnus-cite-1 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#aaccff"))))
 '(gnus-cite-2 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#aadddd"))))
 '(gnus-cite-3 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#aaeecc"))))
 '(gnus-cite-4 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#ff3333"))))
 '(gnus-cite-5 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#ff8888"))))
 '(gnus-cite-6 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#ccaaff"))))
 '(gnus-cite-7 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#aaffaa"))))
 '(gnus-cite-8 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#FF1F69"))))
 '(gnus-cite-9 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#999999"))))
 '(gnus-cite-10 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#5f5f5f"))))
 '(gnus-cite-11 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#292929"))))
 '(gnus-group-mail-1 ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#fcf4dc"))))
 '(gnus-group-mail-1-empty ((t (:foreground "#fcf4dc"))))
 '(gnus-group-mail-2 ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#e9e2cb"))))
 '(gnus-group-mail-2-empty ((t (:foreground "#e9e2cb"))))
 '(gnus-group-mail-3 ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#FF1F69"))))
 '(gnus-group-mail-3-empty ((t (:foreground "#FF1F69"))))
 '(gnus-group-mail-low ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#999999"))))
 '(gnus-group-mail-low-empty ((t (:foreground "#999999"))))
 '(gnus-group-news-1 ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#aaaaaa"))))
 '(gnus-group-news-1-empty ((t (:foreground "#aaaaaa"))))
 '(gnus-group-news-2 ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#aaccff"))))
 '(gnus-group-news-2-empty ((t (:foreground "#aaccff"))))
 '(gnus-group-news-low ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#ccaaff"))))
 '(gnus-group-news-low-empty ((t (:foreground "#ccaaff"))))
 '(gnus-emphasis-highlight-words ((t (:weight normal :slant normal :underline nil :inverse-video nil (:foreground "#aaeecc")))))
 '(gnus-header-content ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#5f5f5f"))))
 '(gnus-header-from ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#999999"))))
 '(gnus-header-name ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#5f5f5f"))))
 '(gnus-header-newsgroups ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#292929"))))
 '(gnus-header-subject ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#aaccff"))))
 '(gnus-server-agent ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#fcf4dc"))))
 '(gnus-server-closed ((t (:weight normal :slant italic :underline nil :inverse-video nil :foreground "#aaaaaa"))))
 '(gnus-server-denied ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#e9e2cb"))))
 '(gnus-server-offline ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#aaffaa"))))
 '(gnus-server-opened ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#aadddd"))))
 '(gnus-signature ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#5f5f5f"))))
 '(gnus-splash ((t (:foreground "#e9e2cb"))))
 '(gnus-summary-cancelled ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#ff3333"))))
 '(gnus-summary-high-ancient ((t (:weight bold :slant normal :underline nil :inverse-video nil :inherit gnus-summary-normal-ancient))))
 '(gnus-summary-high-read ((t (:weight bold :slant normal :underline nil :inverse-video nil :inherit gnus-summary-normal-read))))
 '(gnus-summary-high-ticked ((t (:weight bold :slant normal :underline nil :inverse-video nil :inherit gnus-summary-normal-ticked))))
 '(gnus-summary-high-undownloaded ((t (:weight bold :slant normal :underline nil :inverse-video nil :inherit gnus-summary-normal-undownloaded))))
 '(gnus-summary-high-unread ((t (:weight bold :slant normal :underline nil :inverse-video nil :inherit gnus-summary-normal-unread))))
 '(gnus-summary-low-ancient ((t (:weight normal :slant italic :underline nil :inverse-video nil :inherit gnus-summary-normal-ancient))))
 '(gnus-summary-low-read ((t (:weight normal :slant italic :underline nil :inverse-video nil :inherit gnus-summary-normal-ancient))))
 '(gnus-summary-low-unread ((t (:weight normal :slant italic :underline nil :inverse-video nil :inherit gnus-summary-normal-unread))))
 '(gnus-summary-low-ticked ((t (:weight normal :slant italic :underline nil :inverse-video nil :inherit gnus-summary-normal-ancient))))
 '(gnus-summary-low-undownloaded ((t (:weight normal :slant italic :underline nil :inverse-video nil :inherit gnus-summary-normal-ancient))))
 '(gnus-summary-normal-ancient ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#aaccff"))))
 '(gnus-summary-normal-read ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#5f5f5f"))))
 '(gnus-summary-normal-ticked ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#ff3333"))))
 '(gnus-summary-normal-undownloaded ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#e9e2cb"))))
 '(gnus-summary-normal-unread ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#aaccff"))))
 '(gnus-summary-selected ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#202020" :background "#aaeecc"))))
 '(message-mml ((t (:foreground "#aaccff"))))
 '(message-cited-text ((t (:foreground "#e9e2cb"))))
 '(message-separator ((t (:foreground "#fcf4dc"))))
 '(message-header-xheader ((t (:foreground "#ccaaff"))))
 '(message-header-name ((t (:foreground "#aadddd"))))
 '(message-header-other ((t (:foreground "#ff3333"))))
 '(message-header-newsgroups ((t (:weight bold :underline nil :inverse-video nil :foreground "#aaeecc"))))
 '(message-header-subject ((t (:foreground "#999999"))))
 '(message-header-cc ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#aaffaa"))))
 '(message-header-to ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#aaaaaa"))))
 '(paren-face ((t (:foreground "#5f5f5f"))))
 '(slime-error-face ((t (:weight normal :slant normal :underline nil :inverse-video t :foreground "#ff3333"))))
 '(slime-note-face ((t (:foreground "#aaeecc"))))
 '(slime-repl-inputted-output-face ((t (:foreground "#ff3333"))))
 '(slime-repl-output-mouseover-face ((t (:box (:color "#fcf4dc")))))
 '(slime-style-warning-face ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#ff8888"))))
 '(slime-warning-face ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#ff3333"))))
 '(whitespace-empty ((t (:foreground "#ff3333"))))
 '(whitespace-hspace ((t (:foreground "#ff8888"))))
 '(whitespace-indentation ((t (:foreground "#292929"))))
 '(whitespace-space-after-tab ((t (:foreground "#aadddd"))))
 '(whitespace-space-before-tab ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#ff3333"))))
 '(whitespace-tab ((t (:foreground "#292929"))))
 '(whitespace-trailing ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#ff3333" :background "#292929"))))
 '(whitespace-highlight-face ((t (:foreground "#ff3333" :background "#aaccff"))))
 '(whitespace-line ((t (:foreground "#FF1F69" :background "#202020"))))
 '(rcirc-my-nick ((t (:foreground "#aaccff"))))
 '(rcirc-nick-in-message ((t (:foreground "#ff8888"))))
 '(rcirc-other-nick ((t (:foreground "#aaffaa"))))
 '(rcirc-prompt ((t (:foreground "#aaeecc"))))
 '(rcirc-bright-nick ((t (:foreground "#FF1F69"))))
 '(rcirc-server ((t (:foreground "#aaaaaa"))))
 '(rcirc-timestamp ((t (:foreground "#5f5f5f"))))
 '(erc-nick-defaunoctilux-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#aadddd"))))
 '(font-latex-warning-face ((t (:foreground "#ff3333"))))
 '(font-latex-sectioning-5-face ((t (:foreground "#ccaaff"))))
 '(flyspell-incorrect ((t (:foreground "#ff3333"))))
 '(flyspell-duplicate ((t (:foreground "#aaeecc"))))
 '(term-color-black ((t (:foreground "#292929"))))
 '(term-color-red ((t (:foreground "#ff3333"))))
 '(term-color-green ((t (:foreground "#aaffaa"))))
 '(term-color-yellow ((t (:foreground "#aaeecc"))))
 '(term-color-blue ((t (:foreground "#aaccff"))))
 '(term-color-magenta ((t (:foreground "#FF1F69"))))
 '(term-color-cyan ((t (:foreground "#aadddd"))))
 '(term-color-white ((t (:foreground "#999999")))))

(provide-theme 'Drive-Dark)
